Implement UUID v4 with crypto.getRandomValues()
josefarias/hotwire_combobox pull request #233
Opened 2024-12-17 23:01 UTC by sabljak

This PR implements a custom `randomUUID` function to replace the `crypto.randomUUID` that could not be used in insecure environments due to the nature of `crypto`.

Detailed discussion here https://github.com/josefarias/hotwire_combobox/discussions/223

2024-12-30 07:01 UTC, josefarias commented
Thanks! Taking a look tomorrow

2024-12-30 18:59 UTC, josefarias requested changes
Fantastic @sabljak, thanks a bunch!

Had two small suggestions, then we'll be ready to merge.

2024-12-30 18:59 UTC, josefarias commented on app/assets/javascripts/hw_combobox/models/combobox/callbacks.js
> +import { randomUUID } from "../../helpers";
Does this work?

```suggestion
import { randomUUID } from "hw_combobox/helpers"
```

2024-12-30 18:59 UTC, josefarias commented on app/assets/javascripts/hw_combobox/helpers.js
> +  const uuidPattern = '10000000-1000-4000-8000-100000000000';
Style nit

```suggestion
  const uuidPattern = "10000000-1000-4000-8000-100000000000"
```

2024-12-30 19:09 UTC, sabljak commented
Thanks for the review @josefarias !

I force-pushed the requested changes. 
Now everything should be good to go. 🙌

2024-12-31 00:51 UTC, merged

2024-12-31 00:51 UTC, josefarias commented
Perfect! Thanks @sabljak! Will be part of the next release